%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-ros-gz-sim
Version:        1.0.17
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros_gz_sim package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       cli11-devel
Requires:       gflags-devel
Requires:       ros-jazzy-ament-index-python
Requires:       ros-jazzy-builtin-interfaces
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-gz-math-vendor
Requires:       ros-jazzy-gz-msgs-vendor
Requires:       ros-jazzy-gz-sim-vendor
Requires:       ros-jazzy-gz-transport-vendor
Requires:       ros-jazzy-launch
Requires:       ros-jazzy-launch-ros
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-rclcpp-components
Requires:       ros-jazzy-rcpputils
Requires:       ros-jazzy-ros-gz-interfaces
Requires:       ros-jazzy-std-msgs
Requires:       ros-jazzy-tf2
Requires:       ros-jazzy-tf2-ros
Requires:       ros-jazzy-ros-workspace
BuildRequires:  cli11-devel
BuildRequires:  gflags-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ament-cmake-python
BuildRequires:  ros-jazzy-ament-index-python
BuildRequires:  ros-jazzy-builtin-interfaces
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-gz-math-vendor
BuildRequires:  ros-jazzy-gz-msgs-vendor
BuildRequires:  ros-jazzy-gz-sim-vendor
BuildRequires:  ros-jazzy-gz-transport-vendor
BuildRequires:  ros-jazzy-launch
BuildRequires:  ros-jazzy-launch-ros
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-rclcpp-components
BuildRequires:  ros-jazzy-rcpputils
BuildRequires:  ros-jazzy-ros-gz-interfaces
BuildRequires:  ros-jazzy-std-msgs
BuildRequires:  ros-jazzy-tf2
BuildRequires:  ros-jazzy-tf2-ros
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-lint-auto
BuildRequires:  ros-jazzy-ament-lint-common
BuildRequires:  ros-jazzy-launch-testing
BuildRequires:  ros-jazzy-launch-testing-ament-cmake
%endif

%description
Tools for using Gazebo Sim simulation with ROS.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Wed Jul 16 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.17-1
- Autogenerated by Bloom

* Wed Jul 02 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.16-1
- Autogenerated by Bloom

* Thu Jun 12 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.15-1
- Autogenerated by Bloom

* Mon May 26 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.14-1
- Autogenerated by Bloom

* Fri May 23 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.13-1
- Autogenerated by Bloom

* Tue May 06 2025 Aditya Pande <adityapande@intrinsic.ai> - 1.0.12-1
- Autogenerated by Bloom

* Fri Mar 21 2025 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.11-1
- Autogenerated by Bloom

* Mon Feb 24 2025 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.10-1
- Autogenerated by Bloom

* Wed Feb 12 2025 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.9-1
- Autogenerated by Bloom

* Fri Nov 08 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.7-1
- Autogenerated by Bloom

* Thu Oct 31 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.6-1
- Autogenerated by Bloom

* Mon Oct 14 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.5-1
- Autogenerated by Bloom

* Thu Aug 29 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.4-1
- Autogenerated by Bloom

* Mon Jul 22 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.3-1
- Autogenerated by Bloom

* Wed Jul 03 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.2-1
- Autogenerated by Bloom

* Mon Apr 29 2024 Alejandro Hernandez <ahcorde@openrobotics.org> - 1.0.0-1
- Autogenerated by Bloom

